### ISSUE TITLE
Don't work on safari 5.7.1

### ISSUE THREAD

**Issue by ShootGan** [KrzysztofZawisla/krzysztofzawisla.github.io#137]
Page can't be loaded in safari 5.7.1 on windows. Please fix that.

**Comment by PiotrWieczorek98** [comment]
I have the same problem. Sucks to switch a browser just to checkout the website

**Comment by KrzysztofZawisla** [comment]
@ShootGan @PiotrWieczorek98 I can make a popup for you to remind you about updating the browser to a version newer than the typical BMW e36
